### ISSUE TITLE
Couldn't work with bytes 1.0

### ISSUE THREAD

**Issue by fiag** [rousan/multer-rs#22]
```
error[E0277]: the trait bound `bytes::bytes::Bytes: From<bytes::Bytes>` is not satisfied
  --> src/handlers/my_handler.rs:82:25
   |
82 |     let mut multipart = Multipart::new(stream, boundary);
   |                         ^^^^^^^^^^^^^^ the trait `From<bytes::Bytes>` is not implemented for `bytes::bytes::Bytes`
   | 
  ::: /Users/user/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/multer-1.2.2/src/multipart.rs:59:12
   |
59 |         O: Into<Bytes> + 'static,
   |            ----------- required by this bound in `Multipart::new`
   |
   = help: the following implementations were found:
             <bytes::bytes::Bytes as From<&'static [u8]>>
             <bytes::bytes::Bytes as From<&'static str>>
             <bytes::bytes::Bytes as From<Vec<u8>>>
             <bytes::bytes::Bytes as From<bytes::bytes_mut::BytesMut>>
           and 4 others
   = note: required because of the requirements on the impl of `Into<bytes::bytes::Bytes>` for `bytes::Bytes`
```

**Comment by fiag** [comment]
#21 fix this.

**Comment by nitsky** [comment]
#21 has been merged, multer works with bytes 1.0 now, so this issue can be closed.
